- id: tmaze
  desc: Maze used in Tishby's paper
  code: 
  - gridworld.TishbyMazeOrig
  - {}

- id: rmaze
  desc: Maze used in Rubin's paper
  code: 
  - gridworld.RubinMazeOrig
  - {}
  
- id: tmaze2
  desc: "Maze used in Tishby's paper, with sqrt(2) cost"
  code: 
  - gridworld.TishbyMaze2
  - {}

- id: tmazer
  desc: "Maze with resetting"
  code:
  - gridworld.TishbyMazeReset
  - {}
  
# - id: tmaze2f
#   desc: "Failure in actions (0.3)"
#   code: 
#   - gridworld.TishbyMaze2
#   - fail: 0.3

- id: pomaze1
  desc: "Tishby maze, with failures"
  code:
  - gridworld.POMaze1
  - p_fail: 0.5
    p_loc: 0.5
    
- id: poshape1
  desc: ""
  code:
  - gridworld.POShape1
  - p_fail: 0.5
    p_loc: 0.5