- id: tmaze
  desc: Maze used in Tishby's paper. Actions differ state-by-state.
  code: 
  - gridworld.TishbyMazeOrig
  - {}

- id: tmazb
  desc: Maze used in Tishby's paper. Bumps
  code: 
  - gridworld.TishbyMazeBump
  - bump_reward: -100

- id: tmazbd
  desc: "Maze used in Tishby's paper. Bumps, diagonal"
  code: 
  - gridworld.TishbyMazeBumpD
  - bump_reward: -100


- id: rmaze
  desc: Maze used in Rubin's paper
  code: 
  - gridworld.RubinMazeOrig
  - {}


- id: rmazed
  desc: "Maze used in Rubin's paper, with sqrt(2) cost"
  code: 
  - gridworld.RubinMazeDiag
  - {}


- id: tmazed
  desc: "Maze used in Tishby's paper, with sqrt(2) cost"
  code: 
  - gridworld.TishbyMazeDiag
  - {}

- id: tmazer
  desc: "Maze with resetting"
  code:
  - gridworld.TishbyMazeReset
  - {}
  
# - id: tmaze2f
#   desc: "Failure in actions (0.3)"
#   code: 
#   - gridworld.TishbyMaze2
#   - fail: 0.3

- id: pomaze1
  desc: "Tishby maze, with failures"
  code:
  - gridworld.POMaze1
  - p_fail: 0.5
    p_loc: 0.5
    
- id: poshape1
  desc: ""
  code:
  - gridworld.POShape1
  - p_fail: 0.5
    p_loc: 0.5




- id: "intruder-${map}"
  desc: ""
  code:
  - grid_intruder.IntruderPOMDP
  - gridmap: "${map}"


- id: "pomdp_intruder_${num}"
  desc: ""
  code:
  - grid_intruder.IntruderPOMDP
  - gridmap: "map_intruder_${num}"
