- id: tmaze
  desc: Tishby's maze
  code:
  - gridmaps.map_tmaze
  - {}

- id: rmaze
  desc: Rubin's maze
  code:
  - gridmaps.map_rmaze
  - {}

- id: imap1
  desc: intruder map 1
  code:
  - gridmaps.map_intruder_1
  - {}

- id: imap2
  desc: intruder map 2
  code:
  - gridmaps.map_intruder_2
  - {}

  
- id: imap3
  desc: intruder map 3
  code:
  - gridmaps.map_intruder_3
  - {}


  
- id: imap4
  desc: intruder map 4 (same as imap2 in spirit but only 2 intruders)
  code:
  - gridmaps.map_intruder_4
  - {}


- id: imap6
  desc: "3 rooms, 6 intruders"
  code:
  - gridmaps.map_intruder_6
  - {}


- id: imap5
  desc: intruder map 5 
  code:
  - gridmaps.map_intruder_5
  - {}
